spring.datasource.url=jdbc:postgresql://startup-db:5432/founderlink_startup
spring.datasource.username=postgres
spring.datasource.password=9999
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
